# theme = "base16_transparent"
# theme = "everforest_light"
theme = "everforest_dark"

[editor]
# line-number = "relative"
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left= ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [editor.whitespace.render]
# space = "all"
# tab = "all"
# nbsp = "none"
# nnbsp = "none"
# newline = "none"

# [editor.whitespace.characters]
# space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
# tab = "→"
# #newline = " "
# tabpad = "·" 

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

