#! /bin/sh

sxhkd &
picom -fb &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
